// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package models

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Person struct {
	ID        int32
	Uuid      uuid.UUID
	Name      string
	Nickname  string
	Birthdate time.Time
	Stack     []string
	CreatedAt sql.NullTime
}
